### ISSUE TITLE
BOOT_COMPLETED receiver: Automatically launch an application on start up 

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv#11]
Find a way to automatically start the application immediately after the device starts. 
(Without using another utilility like Android Power Tools)

```
RECEIVE_BOOT_COMPLETED
Allows an application to receive the Intent.ACTION_BOOT_COMPLETED that is broadcast after the system finishes booting.
```

A workaround would be install and use the The Android Power Tools which provides a utility that can be used to automatically launch application(s) after each reboot. 

The utility 'Configure Autorun' can be used to configure which application(s) will be launched after a reboot. 

To configure an application to launch after each reboot:
Select 'Launcher' > 'Powertools' > 'Configure Autorun'.
From the Normal screen, perform a long-tap on the required applications. 
Select 'Yes' to add the application to the Autorun list.
Verify that the selected application is now in the Autorun list.
Reboot the device to verify this functionality.

**Comment by UmarWaqas** [comment]
please try one of the following solutions in order to achieve the Autorun
Possible solutions:
https://stackoverflow.com/questions/53715839/autostart-on-boot-completed-for-flutter-application-based-on-android-example-not
https://askandroidquestions.com/2021/02/18/autostart-flutter-app-on-boot_completed-for-flutter-application-based-on-android-10/
https://github.com/judemanutd/AutoStarter

**Comment by omar-cherif** [comment]
@ismaelAbogabal is this issue dead?

**Comment by ismaelAbogabal** [comment]
Yes, I can say it's dead.

**Comment by omar-cherif** [comment]
Thank you, let's close it then.
